root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o main.exe "
bin = ";export $(grep -v '^#' .env | xargs); ./dist/main.exe"
full_bin = " main.exe"
include_ext = ["go", "tpl", "tmpl", "json", "sql", "yaml", "env"]
exclude_dir = ["tmp", "vendor", "build"]
include_dir = []
exclude_file = []
log = "app.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true